/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 32
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 1
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_ident = 1,
  anon_sym_LPAREN = 2,
  anon_sym_RPAREN = 3,
  anon_sym_COMMA = 4,
  anon_sym_TILDE = 5,
  anon_sym_GT_LT = 6,
  anon_sym_EQ_GT = 7,
  anon_sym_SEMI = 8,
  sym_source_file = 9,
  sym_name = 10,
  sym_agent = 11,
  sym_value = 12,
  sym_arg_list = 13,
  sym_active_pair = 14,
  sym_aplist = 15,
  sym_rule = 16,
  sym_print_stmt = 17,
  sym_stmt = 18,
  aux_sym_source_file_repeat1 = 19,
  aux_sym_arg_list_repeat1 = 20,
  aux_sym_aplist_repeat1 = 21,
  anon_alias_sym_name = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_ident] = "ident",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_TILDE] = "~",
  [anon_sym_GT_LT] = "><",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_SEMI] = ";",
  [sym_source_file] = "source_file",
  [sym_name] = "name",
  [sym_agent] = "agent",
  [sym_value] = "value",
  [sym_arg_list] = "arg_list",
  [sym_active_pair] = "active_pair",
  [sym_aplist] = "aplist",
  [sym_rule] = "rule",
  [sym_print_stmt] = "print_stmt",
  [sym_stmt] = "stmt",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_arg_list_repeat1] = "arg_list_repeat1",
  [aux_sym_aplist_repeat1] = "aplist_repeat1",
  [anon_alias_sym_name] = "name",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_ident] = sym_ident,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_GT_LT] = anon_sym_GT_LT,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_source_file] = sym_source_file,
  [sym_name] = sym_name,
  [sym_agent] = sym_agent,
  [sym_value] = sym_value,
  [sym_arg_list] = sym_arg_list,
  [sym_active_pair] = sym_active_pair,
  [sym_aplist] = sym_aplist,
  [sym_rule] = sym_rule,
  [sym_print_stmt] = sym_print_stmt,
  [sym_stmt] = sym_stmt,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_arg_list_repeat1] = aux_sym_arg_list_repeat1,
  [aux_sym_aplist_repeat1] = aux_sym_aplist_repeat1,
  [anon_alias_sym_name] = anon_alias_sym_name,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_agent] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_list] = {
    .visible = true,
    .named = true,
  },
  [sym_active_pair] = {
    .visible = true,
    .named = true,
  },
  [sym_aplist] = {
    .visible = true,
    .named = true,
  },
  [sym_rule] = {
    .visible = true,
    .named = true,
  },
  [sym_print_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_stmt] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_arg_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_aplist_repeat1] = {
    .visible = false,
    .named = false,
  },
  [anon_alias_sym_name] = {
    .visible = true,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = anon_alias_sym_name,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '(') ADVANCE(5);
      if (lookahead == ')') ADVANCE(6);
      if (lookahead == ',') ADVANCE(7);
      if (lookahead == ';') ADVANCE(11);
      if (lookahead == '=') ADVANCE(2);
      if (lookahead == '>') ADVANCE(1);
      if (lookahead == '~') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(4);
      END_STATE();
    case 1:
      if (lookahead == '<') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == '>') ADVANCE(10);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(4);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_GT_LT);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_GT_LT] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(26),
    [sym_name] = STATE(15),
    [sym_agent] = STATE(7),
    [sym_value] = STATE(21),
    [sym_active_pair] = STATE(14),
    [sym_aplist] = STATE(27),
    [sym_rule] = STATE(27),
    [sym_print_stmt] = STATE(27),
    [sym_stmt] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_ident] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(5), 1,
      sym_ident,
    ACTIONS(7), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      sym_agent,
    STATE(14), 1,
      sym_active_pair,
    STATE(15), 1,
      sym_name,
    STATE(21), 1,
      sym_value,
    STATE(3), 2,
      sym_stmt,
      aux_sym_source_file_repeat1,
    STATE(27), 3,
      sym_aplist,
      sym_rule,
      sym_print_stmt,
  [28] = 8,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      sym_ident,
    STATE(7), 1,
      sym_agent,
    STATE(14), 1,
      sym_active_pair,
    STATE(15), 1,
      sym_name,
    STATE(21), 1,
      sym_value,
    STATE(3), 2,
      sym_stmt,
      aux_sym_source_file_repeat1,
    STATE(27), 3,
      sym_aplist,
      sym_rule,
      sym_print_stmt,
  [56] = 2,
    ACTIONS(14), 1,
      anon_sym_LPAREN,
    ACTIONS(16), 6,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_TILDE,
      anon_sym_GT_LT,
      anon_sym_EQ_GT,
      anon_sym_SEMI,
  [68] = 6,
    ACTIONS(5), 1,
      sym_ident,
    ACTIONS(18), 1,
      anon_sym_SEMI,
    STATE(14), 1,
      sym_active_pair,
    STATE(29), 1,
      sym_value,
    STATE(31), 1,
      sym_aplist,
    STATE(7), 2,
      sym_name,
      sym_agent,
  [88] = 5,
    ACTIONS(5), 1,
      sym_ident,
    ACTIONS(20), 1,
      anon_sym_RPAREN,
    STATE(17), 1,
      sym_value,
    STATE(28), 1,
      sym_arg_list,
    STATE(7), 2,
      sym_name,
      sym_agent,
  [105] = 1,
    ACTIONS(22), 6,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_TILDE,
      anon_sym_GT_LT,
      anon_sym_EQ_GT,
      anon_sym_SEMI,
  [114] = 1,
    ACTIONS(24), 6,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_TILDE,
      anon_sym_GT_LT,
      anon_sym_EQ_GT,
      anon_sym_SEMI,
  [123] = 1,
    ACTIONS(26), 6,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_TILDE,
      anon_sym_GT_LT,
      anon_sym_EQ_GT,
      anon_sym_SEMI,
  [132] = 4,
    ACTIONS(5), 1,
      sym_ident,
    STATE(24), 1,
      sym_active_pair,
    STATE(29), 1,
      sym_value,
    STATE(7), 2,
      sym_name,
      sym_agent,
  [146] = 3,
    ACTIONS(5), 1,
      sym_ident,
    STATE(30), 1,
      sym_value,
    STATE(7), 2,
      sym_name,
      sym_agent,
  [157] = 3,
    ACTIONS(5), 1,
      sym_ident,
    STATE(23), 1,
      sym_value,
    STATE(7), 2,
      sym_name,
      sym_agent,
  [168] = 3,
    ACTIONS(5), 1,
      sym_ident,
    STATE(25), 1,
      sym_value,
    STATE(7), 2,
      sym_name,
      sym_agent,
  [179] = 3,
    ACTIONS(28), 1,
      anon_sym_COMMA,
    ACTIONS(30), 1,
      anon_sym_SEMI,
    STATE(16), 1,
      aux_sym_aplist_repeat1,
  [189] = 2,
    ACTIONS(32), 1,
      anon_sym_SEMI,
    ACTIONS(22), 2,
      anon_sym_TILDE,
      anon_sym_GT_LT,
  [197] = 3,
    ACTIONS(28), 1,
      anon_sym_COMMA,
    ACTIONS(34), 1,
      anon_sym_SEMI,
    STATE(19), 1,
      aux_sym_aplist_repeat1,
  [207] = 3,
    ACTIONS(36), 1,
      anon_sym_RPAREN,
    ACTIONS(38), 1,
      anon_sym_COMMA,
    STATE(18), 1,
      aux_sym_arg_list_repeat1,
  [217] = 3,
    ACTIONS(38), 1,
      anon_sym_COMMA,
    ACTIONS(40), 1,
      anon_sym_RPAREN,
    STATE(20), 1,
      aux_sym_arg_list_repeat1,
  [227] = 3,
    ACTIONS(42), 1,
      anon_sym_COMMA,
    ACTIONS(45), 1,
      anon_sym_SEMI,
    STATE(19), 1,
      aux_sym_aplist_repeat1,
  [237] = 3,
    ACTIONS(47), 1,
      anon_sym_RPAREN,
    ACTIONS(49), 1,
      anon_sym_COMMA,
    STATE(20), 1,
      aux_sym_arg_list_repeat1,
  [247] = 2,
    ACTIONS(52), 1,
      anon_sym_TILDE,
    ACTIONS(54), 1,
      anon_sym_GT_LT,
  [254] = 1,
    ACTIONS(56), 2,
      ts_builtin_sym_end,
      sym_ident,
  [259] = 1,
    ACTIONS(58), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
  [264] = 1,
    ACTIONS(45), 2,
      anon_sym_COMMA,
      anon_sym_SEMI,
  [269] = 1,
    ACTIONS(47), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [274] = 1,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
  [278] = 1,
    ACTIONS(62), 1,
      anon_sym_SEMI,
  [282] = 1,
    ACTIONS(64), 1,
      anon_sym_RPAREN,
  [286] = 1,
    ACTIONS(52), 1,
      anon_sym_TILDE,
  [290] = 1,
    ACTIONS(66), 1,
      anon_sym_EQ_GT,
  [294] = 1,
    ACTIONS(68), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 28,
  [SMALL_STATE(4)] = 56,
  [SMALL_STATE(5)] = 68,
  [SMALL_STATE(6)] = 88,
  [SMALL_STATE(7)] = 105,
  [SMALL_STATE(8)] = 114,
  [SMALL_STATE(9)] = 123,
  [SMALL_STATE(10)] = 132,
  [SMALL_STATE(11)] = 146,
  [SMALL_STATE(12)] = 157,
  [SMALL_STATE(13)] = 168,
  [SMALL_STATE(14)] = 179,
  [SMALL_STATE(15)] = 189,
  [SMALL_STATE(16)] = 197,
  [SMALL_STATE(17)] = 207,
  [SMALL_STATE(18)] = 217,
  [SMALL_STATE(19)] = 227,
  [SMALL_STATE(20)] = 237,
  [SMALL_STATE(21)] = 247,
  [SMALL_STATE(22)] = 254,
  [SMALL_STATE(23)] = 259,
  [SMALL_STATE(24)] = 264,
  [SMALL_STATE(25)] = 269,
  [SMALL_STATE(26)] = 274,
  [SMALL_STATE(27)] = 278,
  [SMALL_STATE(28)] = 282,
  [SMALL_STATE(29)] = 286,
  [SMALL_STATE(30)] = 290,
  [SMALL_STATE(31)] = 294,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [11] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [14] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [16] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name, 1, 0, 1),
  [18] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 4, 0, 0),
  [20] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [22] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_agent, 4, 0, 0),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_agent, 3, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_aplist, 1, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_print_stmt, 1, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_aplist, 2, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 2, 0, 0),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_aplist_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_aplist_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_arg_list_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stmt, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_active_pair, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule, 5, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pinet(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "pinet",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
